branches:
  - master
build:
  main_build:
    image: node:6
    environment:
      TOKEN: $$TOKEN
    commands:
      - cd $DRONE_DIR
      - ls -a
      - cat README.md
      - echo $TOKEN
      - git log
    when:
      branch: master
deploy:
  git_push:
    branch: release
    remote: https://github.com/3846masa/drone.io-test.git
    force: false
    when:
      branch: master
